### ISSUE TITLE
firefox?

### ISSUE THREAD

**Issue by Noitidart** [arcanous/angular-gallery#1]
hi there i tried to use this, i downloaded the master and opened index.html but i get this error:

![](http://i.imgur.com/6gq5Ppb.png)

Can you please help me to get it to work. :)

**Comment by arcanous** [comment]
Yes, you should not open the index.html directly from filesystem.

You should place it on a webserver and open it via URL.

For example, you can install https://www.npmjs.com/package/http-server, navigate to the directory in the terminal and launch webserver from there.

![image](https://cloud.githubusercontent.com/assets/4963067/10157657/26ea93e0-668c-11e5-825b-9a74be345173.png)

**Comment by Noitidart** [comment]
Thanks very nice work!
